# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beerworld' do

	use_frameworks!

	pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON'
    pod 'CSV.swift', '~> 2.1.0'

end
